import { demoInput, domesticStaffles } from './config/defaults.js';
import { buildQuoteSummary, calculateAlternativeModality, calculateScenarioCheapest, calculateScenarioFastest } from './services/scenarioCalculator.js';
import { ScenarioResult, TripInput } from './types.js';

let input: TripInput = structuredClone(demoInput);
let scenarios: ScenarioResult[] = [];
let selectedId = '';
let quoteText = '';
let loading = false;
let errors: string[] = [];

const root = document.getElementById('root')!;
render();
void calculate();

async function calculate() {
  errors = validateInput(input);
  if (errors.length) { render(); return; }
  loading = true; render();
  try {
    const fastest = await calculateScenarioFastest(input);
    const cheapest = await calculateScenarioCheapest(input);
    const alternative = await calculateAlternativeModality(input);
    scenarios = [fastest, { ...cheapest, recommended: cheapest.cost.totalIncVat <= fastest.cost.totalIncVat }, alternative].filter(Boolean) as ScenarioResult[];
    selectedId = fastest.id;
    quoteText = await buildQuoteSummary(input, fastest);
  } finally { loading = false; render(); }
}

function render() {
  const selected = scenarios.find((scenario) => scenario.id === selectedId) || scenarios[0];
  root.innerHTML = `<div class="app-shell">${renderConfig()}<main class="workspace">${renderHero()}${renderMap(selected)}${renderWarnings(selected)}${renderScenarios(selected)}${selected ? renderQuote(selected) : ''}</main></div>`;
  bindEvents();
}

function renderHero() {
  return `<header class="hero"><div><p class="eyebrow">Interne tool · reviewversie</p><h1>Snelle, realistische kosteninschatting voor Autoreset-ritten</h1><p>Configureer links de volledige rondtrip van chauffeur en voertuig; vergelijk rechts snelste, goedkoopste en alternatieve modaliteit.</p></div><div class="status-card"><span class="icon ok">✓</span><strong>Demo/fallbackmodus klaar</strong><span>HERE API kan via instellingen of .env worden gekoppeld.</span></div></header>`;
}

function renderConfig() {
  return `<aside class="config-panel"><div class="brand"><div class="logo">AR</div><div><strong>Autoreset</strong><span>Offertecalculator ritten</span></div></div>${errors.length ? `<div class="alert danger">${errors.map((e) => `<p>${e}</p>`).join('')}</div>` : ''}
  <section class="panel-section"><h2>1. Basisgegevens</h2>${textInput('homeAddress','Woonadres chauffeur')}${textInput('pickupAddress','Ophaaladres')}${textInput('deliveryAddress','Afleveradres')}${textInput('returnAddress','Retouradres optioneel')}
  <div class="two">${textInput('departureDate','Datum vertrek','date')}${textInput('departureTime','Tijd','time')}</div>${toggle('useArrivalTime','Gewenste aankomsttijd i.p.v. vertrek')}${toggle('hasReturnVehicle','Retourvoertuig aanwezig')}${toggle('isDomestic','Rit binnen Nederland')}${toggle('isWaddenIsland','Waddeneiland')}${toggle('useDomesticStaffle','Gebruik vaste prijs/staffel')}</section>
  <section class="panel-section"><h2>2. Voertuigen</h2><label>Voertuig heenrit${vehicleSelect('vehicle.type', input.vehicle.type)}</label>${input.hasReturnVehicle ? `<label>Retourvoertuig${vehicleSelect('returnVehicle.type', input.returnVehicle.type)}</label>` : ''}<label>Bijzonderheden voertuig<textarea data-field="vehicle.notes" placeholder="Bijv. hoogte, schade, laadruimte, brandstof">${escapeHtml(input.vehicle.notes)}</textarea></label></section>
  <section class="panel-section"><h2>3. Tarieven en toeslagen</h2><div class="rate-grid">${numberInput('hourlyRate','Uurtarief chauffeur')}${numberInput('hotelNight','Hotelovernachting')}${numberInput('mealDay','Maaltijdvergoeding')}${numberInput('taxiPerKm','Taxi €/km','0.1')}${numberInput('taxiStart','Taxi starttarief')}${numberInput('maxDrivingHoursPerDay','Max rijtijd/dag')}${numberInput('maxWorkHoursPerDay','Max werkdag')}${numberInput('transferBufferMinutes','Overstapbuffer min')}${numberInput('airportPreBufferMinutes','Vliegbuffer vóór')}${numberInput('airportPostBufferMinutes','Buffer na landing')}${numberInput('kilometerComponent','Km component','0.01')}${numberInput('marginPercent','Marge %')}${numberInput('vatPercent','BTW %')}</div></section>
  <section class="panel-section"><h2>4. Prijsbronnen</h2>${textInput('hereApiKey','HERE API key','password','YOUR_HERE_API_KEY_HERE')}<p class="hint">Gebruik in productie een server/proxy; frontend keys zijn zichtbaar in de browser.</p><select data-field="priceSource"><option value="live-first" ${input.priceSource === 'live-first' ? 'selected' : ''}>Live data waar beschikbaar</option><option value="fallback" ${input.priceSource === 'fallback' ? 'selected' : ''}>Indicatieve fallback gebruiken</option></select><div class="settings-panel"><h3>Voorbeeldstaffels binnen Nederland</h3><p>Vervang deze voorbeeldtabel door echte Autoreset-tarieven.</p><div class="staffle-grid">${domesticStaffles.map((r) => `<span>${r.label}<strong>€${r.price}</strong></span>`).join('')}</div></div></section>
  <section class="panel-section actions"><h2>5. Acties</h2><button class="primary" data-action="calculate">⌁ ${loading ? 'Berekenen...' : 'Bereken offerte'}</button><button data-action="reset">↺ Reset</button><button data-action="export">⇩ Exporteer offerte</button><button data-action="copy">⧉ Kopieer samenvatting</button></section></aside>`;
}

function renderMap(scenario?: ScenarioResult) {
  const points = scenario?.segments.flatMap((segment) => segment.path?.length ? segment.path : [{ lat: segment.start.lat ?? 52, lng: segment.start.lng ?? 5 }, { lat: segment.end.lat ?? 52, lng: segment.end.lng ?? 5 }]) ?? [];
  const bounds = getBounds(points);
  const toSvg = (lat: number, lng: number) => ({ x: ((lng - bounds.minLng) / (bounds.maxLng - bounds.minLng || 1)) * 88 + 6, y: 94 - ((lat - bounds.minLat) / (bounds.maxLat - bounds.minLat || 1)) * 82 });
  const paths = scenario?.segments.map((segment, index) => { const path = segment.path?.length ? segment.path : [{ lat: segment.start.lat ?? 52, lng: segment.start.lng ?? 5 }, { lat: segment.end.lat ?? 52, lng: segment.end.lng ?? 5 }]; const d = path.map((p, i) => `${i ? 'L' : 'M'} ${toSvg(p.lat, p.lng).x} ${toSvg(p.lat, p.lng).y}`).join(' '); return `<path d="${d}" class="route-line route-${segment.modality}"></path>`; }).join('') ?? '';
  const markers = scenario?.segments.flatMap((s) => [s.start, s.end]).map((address, index) => { const p = toSvg(address.lat ?? 52, address.lng ?? 5); return `<g><circle cx="${p.x}" cy="${p.y}" r="1.8" fill="#0f172a"></circle><text x="${p.x + 2}" y="${p.y - 1}" font-size="3">${escapeHtml(address.label.split(',')[0])}</text></g>`; }).join('') ?? '';
  return `<div class="map-card"><div class="map-toolbar"><div><strong>Routekaart</strong><span>HERE-ready kaartweergave met fallback routeplot</span></div><span class="badge quality-indicative">Map tiles via HERE config</span></div><svg class="route-map" viewBox="0 0 100 100" role="img"><defs><linearGradient id="water" x1="0" x2="1"><stop stop-color="#e7f2ff"/><stop offset="1" stop-color="#f7fbff"/></linearGradient></defs><rect width="100" height="100" rx="4" fill="url(#water)"/><path d="M2 78 C20 62 35 70 50 50 C62 34 78 39 98 18" fill="none" stroke="#d5e4f4" stroke-width="10"/>${paths}${markers}</svg><div class="legend"><span class="road">Voertuigrit</span><span class="train">Trein/OV</span><span class="flight">Vlucht</span><span class="taxi">Taxi</span></div>${!scenario ? '<div class="empty-map">⌖ Bereken een offerte om route(s), markers en segmenten te tonen.</div>' : ''}</div>`;
}

function renderWarnings(scenario?: ScenarioResult) { const warnings = scenario?.warnings.length ? scenario.warnings : ['API-data ontbreekt mogelijk; fallbackprijzen worden zichtbaar gemarkeerd.', 'Vlucht-/treinprijs niet live beschikbaar zonder gekoppelde prijs-API.']; return `<section class="warnings"><h2>⚠ Aandachtspunten</h2><div>${warnings.map((w) => `<span>${escapeHtml(w)}</span>`).join('')}</div></section>`; }
function renderScenarios(selected?: ScenarioResult) { return `<div class="scenario-grid">${scenarios.map((s) => `<button class="scenario-card ${s.tone} ${selected?.id === s.id ? 'selected' : ''}" data-select="${s.id}"><div class="card-head"><span class="badge">${s.badge}</span>${s.recommended ? '<span class="badge recommended">Aanbevolen</span>' : ''}<span class="badge quality-${s.dataQuality}">${qualityLabel(s.dataQuality)}</span></div><h3>${s.title}</h3><div class="price">€${s.cost.totalIncVat}<small> incl. BTW</small></div><div class="metrics"><span>◷ ${fmt(s.totalDurationMinutes)}</span><span>⌁ ${s.totalDistanceKm} km</span><span>▣ ${s.cost.hotelNights} nacht(en)</span><span>€ ${s.cost.totalExVat} excl.</span></div><p>${s.explanation}</p><div class="modalities">${s.modalities.map((m) => `<span>${m}</span>`).join('')}</div>${s.warnings.slice(0,2).map((w) => `<small class="warning">${escapeHtml(w)}</small>`).join('')}</button>`).join('')}</div>`; }
function renderQuote(s: ScenarioResult) { return `<section class="quote-summary" id="quote-summary"><h2>Indicatieve offerte Autoreset rit</h2><p class="muted">Berekening gemaakt op ${new Date().toLocaleString('nl-NL')} · prijzen onder voorbehoud van beschikbaarheid en actuele reiskosten.</p><div class="summary-grid"><div><h3>Ingevoerde adressen</h3><p>Thuis: ${input.homeAddress}</p><p>Ophalen: ${input.pickupAddress}</p><p>Afleveren: ${input.deliveryAddress}</p><p>Retour: ${input.hasReturnVehicle ? input.returnAddress : 'Geen retourvoertuig; chauffeur reist terug naar huis'}</p><h3>Voertuiggegevens</h3><p>${input.vehicle.type} ${input.vehicle.notes}</p></div>${costTable(s)}</div>${timeline(s)}<div class="assumptions"><h3>Aannames en waarschuwingen</h3><ul><li>De tool geeft een indicatieve offerte.</li><li>Ticketprijzen zijn alleen definitief als ze live via een gekoppelde API zijn opgehaald.</li><li>Hotel- en maaltijdkosten zijn configureerbare standaardbedragen.</li><li>Binnenlandse staffels moeten worden vervangen door de echte Autoreset-tarieven.</li><li>Waddeneilanden vereisen aanvullende ferry-/wachttijdlogica.</li><li>Overnachtingstijd telt niet mee als werktijd.</li>${s.warnings.map((w) => `<li>${escapeHtml(w)}</li>`).join('')}</ul></div><details><summary>Tekst voor export/kopie</summary><pre>${escapeHtml(quoteText)}</pre></details></section>`; }
function costTable(s: ScenarioResult) { const c = s.cost; const rows = [['Chauffeursuren', `${c.driverHours} uur`, c.driverCost], ['Wegafstand / staffel', `${Math.round(c.roadDistanceKm)} km`, c.roadCost], ['OV', '', c.publicTransportCost], ['Trein', '', c.trainCost], ['Vlucht', '', c.flightCost], ['Taxi', '', c.taxiCost], ['Hotel', `${c.hotelNights} nacht(en)`, c.hotelCost], ['Maaltijden', `${c.mealDays} dag(en)`, c.mealCost], ['Toeslagen', '', c.surcharges], ['Marge', '', c.margin], ['BTW', '', c.vat]]; return `<table class="cost-table"><tbody>${rows.map(([l,m,a]) => `<tr><td>${l}<small>${m}</small></td><td>€${a}</td></tr>`).join('')}<tr class="total"><td>Totaal excl. BTW</td><td>€${c.totalExVat}</td></tr><tr class="grand"><td>Totaal incl. BTW</td><td>€${c.totalIncVat}</td></tr></tbody></table>`; }
function timeline(s: ScenarioResult) { return `<div class="timeline"><h3>Routebeschrijving per segment</h3>${s.segments.map((seg,i) => `<div class="timeline-item"><span>${i+1}</span><div><strong>${seg.description}</strong><p>${seg.start.label} → ${seg.end.label}</p><small>${seg.modality} · ${seg.durationMinutes} min · ${seg.distanceKm} km · €${seg.cost} · ${seg.source} · confidence ${seg.confidence}</small></div></div>`).join('')}</div>`; }

function bindEvents() { document.querySelectorAll<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>('[data-field]').forEach((el) => el.addEventListener('input', () => updateField(el.dataset.field!, el.type === 'checkbox' ? (el as HTMLInputElement).checked : el.value))); document.querySelector('[data-action="calculate"]')?.addEventListener('click', () => void calculate()); document.querySelector('[data-action="reset"]')?.addEventListener('click', () => { input = structuredClone(demoInput); scenarios = []; selectedId = ''; render(); void calculate(); }); document.querySelector('[data-action="copy"]')?.addEventListener('click', () => navigator.clipboard?.writeText(quoteText)); document.querySelector('[data-action="export"]')?.addEventListener('click', exportQuote); document.querySelectorAll<HTMLElement>('[data-select]').forEach((el) => el.addEventListener('click', async () => { selectedId = el.dataset.select!; const s = scenarios.find((x) => x.id === selectedId); if (s) quoteText = await buildQuoteSummary(input, s); render(); })); }
function updateField(field: string, value: string | boolean) { if (field in input) (input as unknown as Record<string, string | boolean>)[field] = value; else if (field.startsWith('vehicle.')) (input.vehicle as unknown as Record<string,string>)[field.split('.')[1]] = String(value); else if (field.startsWith('returnVehicle.')) (input.returnVehicle as unknown as Record<string,string>)[field.split('.')[1]] = String(value); else input.pricing[field as keyof TripInput['pricing']] = Number(value); }
function exportQuote() { const blob = new Blob([quoteText], { type: 'text/plain;charset=utf-8' }); const href = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = href; link.download = 'indicatieve-offerte-autoreset.txt'; link.click(); URL.revokeObjectURL(href); }
function validateInput(i: TripInput) { const e: string[] = []; if (!i.homeAddress.trim()) e.push('Vul het woonadres van de chauffeur in.'); if (!i.pickupAddress.trim()) e.push('Vul het ophaaladres in.'); if (!i.deliveryAddress.trim()) e.push('Vul het afleveradres in.'); if (i.pricing.hourlyRate <= 0) e.push('Uurtarief chauffeur moet groter zijn dan 0.'); return e; }
function textInput(field: keyof TripInput, label: string, type = 'text', placeholder = '') { return `<label>${label}<input data-field="${String(field)}" type="${type}" value="${escapeHtml(String(input[field] ?? ''))}" placeholder="${placeholder}" /></label>`; }
function numberInput(field: keyof TripInput['pricing'], label: string, step='1') { return `<label>${label}<input data-field="${String(field)}" type="number" step="${step}" value="${input.pricing[field]}" /></label>`; }
function toggle(field: keyof TripInput, label: string) { return `<label class="toggle"><input data-field="${String(field)}" type="checkbox" ${input[field] ? 'checked' : ''}/><span>${label}</span></label>`; }
function vehicleSelect(field: string, value: string) { return `<select data-field="${field}">${['Personenauto','Bestelauto','Bakwagen','Vrachtwagen','Camper','Anders'].map((v) => `<option ${v === value ? 'selected' : ''}>${v}</option>`).join('')}</select>`; }
function getBounds(points: Array<{ lat: number; lng: number }>) { if (!points.length) return { minLat: 47, maxLat: 53, minLng: 3, maxLng: 12 }; return { minLat: Math.min(...points.map((p) => p.lat)) - .3, maxLat: Math.max(...points.map((p) => p.lat)) + .3, minLng: Math.min(...points.map((p) => p.lng)) - .3, maxLng: Math.max(...points.map((p) => p.lng)) + .3 }; }
function qualityLabel(q: string) { return ({ live: 'Live data', calculated: 'Berekend', indicative: 'Indicatief', fallback: 'Fallback' } as Record<string,string>)[q]; }
function fmt(minutes: number) { return `${Math.floor(minutes / 60)}u ${minutes % 60}m`; }
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]!)); }
